---
openapi: 3.0.0
info:
  title: Account Management
  description: This is the API specifications that has been done by Emre Kutuk
  contact:
    email: 644853@student.inholland.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
- {}
security:
- bearerAuth: []
paths:
  /Accounts/{id}:
    summary: Represents an account
    description: |
      This resource represents and individual account in the system. Each account is identified by a number id.
    get:
      tags:
      - AccountManagement
      summary: Gets an account by ID.
      operationId: getAccountById
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An account object has been returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAll'
    put:
      tags:
      - AccountManagement
      summary: Updates an existing account
      operationId: updateAccountById
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAll'
        required: true
      responses:
        "200":
          description: An account object has been updated
    delete:
      tags:
      - AccountManagement
      summary: Deletes an account by ID
      operationId: deleteAccountById
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: The account object has been deleted
  /Accounts/{id}/{type}:
    summary: Represents an account type
    description: |
      This resource represents and individual account type in the system. Each account is identified by a number id.
    post:
      tags:
      - AccountType
      summary: Changes account type
      operationId: changeAccountType
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      - name: type
        in: path
        description: The new type
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - saving
          - current
      responses:
        "200":
          description: The account type has been changed
  /Accounts:
    summary: Represents an account object
    description: |
      This resource represents and individual account object in the system. Each account is identified by a number id.
    get:
      tags:
      - AccountManagement
      summary: Gets all accounts
      operationId: getAllAccounts
      parameters:
      - name: offset
        in: query
        description: The number of accounts to skip before starting to collect the result set.
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
      - name: limit
        in: query
        description: The numbers of accounts to return.
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 1
          type: integer
          default: 20
      responses:
        "200":
          description: Paginated accounts have been returned
    post:
      tags:
      - AccountManagement
      summary: Adds a new Account
      operationId: addANewAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        "201":
          description: New account has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /Accounts/{id}/addBalance/{amount}:
    summary: Represents an account balance and the amount that needs to be added
    description: |
      This resource represents an amount and the amount that needs to be added to an account. Each account is identified by a number id.
    post:
      tags:
      - AccountBalance
      summary: Adds specified amount
      operationId: addBalance
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      - name: amount
        in: path
        description: Balance to be added
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: number
      responses:
        "200":
          description: The amount has been added to the account
  /Accounts/{id}/subtractBalance/{amount}:
    summary: Represents an account balance and the amount that needs to be subtracted
    description: |
      This resource represents the amount that needs to be subtracted to added to an account. Each account is identified by a number id.
    post:
      tags:
      - AccountBalance
      summary: Subtracts specified amount
      operationId: subtractBalance
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      - name: amount
        in: path
        description: Balance to be subtracted
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: number
      responses:
        "200":
          description: The amount has been subtracted from the account
  /Accounts/{id}/getBalance:
    summary: Represents an account balance
    description: |
      This resource represents an account's balance. Each account is identified by a number id.
    get:
      tags:
      - AccountBalance
      summary: Gets an account balance by ID.
      operationId: getAccountBalanceById
      parameters:
      - name: id
        in: path
        description: Account ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: Balance of the account has been returned
components:
  schemas:
    Account:
      required:
      - accountType
      - balance
      - iban
      - id
      - password
      type: object
      properties:
        id:
          minimum: 1
          type: integer
          description: The unique id of the account
          format: int64
          example: 3
        iban:
          type: string
          not: {}
          description: IBAN number of the account
          example: NL03INHO0033576852
        accountType:
          type: string
          description: Type of the account, can be either saving or current
          default: current
          enum:
          - saving
          - current
        balance:
          minimum: 0
          type: number
          format: float
          default: 0
    AccountAll:
      required:
      - accountType
      - balance
      - iban
      - id
      - password
      type: object
      properties:
        id:
          minimum: 1
          type: integer
          description: The unique id of the account
          format: int64
          example: 3
        iban:
          type: string
          description: IBAN number of the account
          example: NL03INHO0033576852
        accountType:
          type: string
          description: Type of the account, can be either saving or current
          default: current
          enum:
          - saving
          - current
        balance:
          minimum: 0
          type: number
          format: float
          default: 0
  parameters:
    offsetParam:
      name: offset
      in: query
      description: The number of accounts to skip before starting to collect the result set.
      required: false
      style: form
      explode: true
      schema:
        minimum: 0
        type: integer
    limitParam:
      name: limit
      in: query
      description: The numbers of accounts to return.
      required: false
      style: form
      explode: true
      schema:
        maximum: 50
        minimum: 1
        type: integer
        default: 20
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
